USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MOBILITY_DEV;
USE DATABASE MOBILITY_DEMO;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE TAXI_ZONE_LOOKUP (
    LOCATION_ID NUMBER,
    BOROUGH STRING,
    ZONE STRING,
    SERVICE_ZONE STRING
);

SELECT 'TAXI_ZONE_LOOKUP table created' AS status;

select count(*) AS row_count
from taxi_zone_lookup;


SELECT * 
FROM TAXI_ZONE_LOOKUP
ORDER BY LOCATION_ID
LIMIT 20;

SELECT 
    BOROUGH,
    COUNT(*) AS zones_count
FROM TAXI_ZONE_LOOKUP
GROUP BY BOROUGH
ORDER BY zones_count DESC;