USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MOBILITY_DEV;
USE DATABASE MOBILITY_DEMO;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE YELLOW_TAXI_TRIPS (
    VENDOR_ID NUMBER,
    PICKUP_DATETIME NUMBER,
    DROPOFF_DATETIME NUMBER,
    PASSENGER_COUNT NUMBER,
    TRIP_DISTANCE FLOAT,
    RATE_CODE_ID NUMBER,
    STORE_AND_FWD_FLAG STRING,
    PU_LOCATION_ID NUMBER,
    DO_LOCATION_ID NUMBER,
    PAYMENT_TYPE NUMBER,
    FARE_AMOUNT FLOAT,
    EXTRA FLOAT,
    MTA_TAX FLOAT,
    TIP_AMOUNT FLOAT,
    TOLLS_AMOUNT FLOAT,
    IMPROVEMENT_SURCHARGE FLOAT,
    TOTAL_AMOUNT FLOAT,
    CONGESTION_SURCHARGE FLOAT,
    AIRPORT_FEE FLOAT,
    SOURCE_FILE STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE YELLOW_TAXI_TRIPS 
ADD COLUMN EXTRA FLOAT;

ALTER TABLE YELLOW_TAXI_TRIPS
ADD COLUMN DROPOFF_NUMERIC NUMBER(38);

UPDATE YELLOW_TAXI_TRIPS
SET DROPOFF_DATETIME = TO_TIMESTAMP_NTZ(DROPOFF_NUMERIC, 6);

SELECT * FROM YELLOW_TAXI_TRIPS
LIMIT 10;

ALTER TABLE YELLOW_TAXI_TRIPS
DROP COLUMN DROPOFF_NUMERIC;

DROP TABLE YELLOW_TAXI_TRIPS;

