USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MOBILITY_DEV;
USE DATABASE MOBILITY_DEMO;

-- 1. Schemas.
SHOW SCHEMAS IN DATABASE MOBILITY_DEMO;

-- 2. Tables.
SHOW TABLES IN DATABASE MOBILITY_DEMO;

-- 3. Views.
SHOW VIEWS IN DATABASE MOBILITY_DEMO;

-- 4. Row counts for important objects.
SELECT
    'RAW.TAXI_ZONE_LOOKUP' AS object_name,
    COUNT(*) AS row_count
FROM RAW.TAXI_ZONE_LOOKUP

UNION ALL

SELECT
    'SILVER.YELLOW_TAXI_TRIPS_CLEAN' AS object_name,
    COUNT(*) AS row_count
FROM SILVER.YELLOW_TAXI_TRIPS_CLEAN

UNION ALL

SELECT
    'SILVER.YELLOW_TAXI_TRIPS_VALID' AS object_name,
    COUNT(*) AS row_count
FROM SILVER.YELLOW_TAXI_TRIPS_VALID

UNION ALL

SELECT
    'GOLD.PICKUP_ZONE_METRICS' AS object_name,
    COUNT(*) AS row_count
FROM GOLD.PICKUP_ZONE_METRICS

UNION ALL

SELECT
    'GOLD.HOURLY_PICKUP_DEMAND' AS object_name,
    COUNT(*) AS row_count
FROM GOLD.HOURLY_PICKUP_DEMAND

UNION ALL

SELECT
    'GOLD.ROUTE_REVENUE_METRICS' AS object_name,
    COUNT(*) AS row_count
FROM GOLD.ROUTE_REVENUE_METRICS;