USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MOBILITY_DEV;
USE DATABASE MOBILITY_DEMO;

-- Final Week 1 project summary.

SELECT 'PIPELINE SUMMARY' AS section;
SELECT *
FROM OPS.PIPELINE_SUMMARY;

SELECT 'TAXI DATA QUALITY REPORT' AS section;
SELECT *
FROM OPS.DATA_QUALITY_REPORT;

SELECT 'TAXI BUSINESS HIGHLIGHTS' AS section;
SELECT *
FROM OPS.BUSINESS_HIGHLIGHTS;


SELECT 'WEATHER QUALITY REPORT' AS section;
SELECT *
FROM OPS.WEATHER_QUALITY_REPORT;

SELECT 'WEATHER BUSINESS SUMMARY' AS section;

SELECT *
FROM OPS.WEATHER_BUSINESS_SUMMARY;

SELECT 'WEATHER IMPACT BY BUCKET' AS section;

SELECT *
FROM GOLD.WEATHER_IMPACT_BY_BUCKET
ORDER BY temperature_bucket, has_precipitation;

SELECT 'TOP WEATHER DEMAND HOURS' AS section;

SELECT *
FROM GOLD.TOP_WEATHER_DEMAND_HOURS
ORDER BY trips_count DESC
LIMIT 20;