USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MOBILITY_DEV;
USE DATABASE MOBILITY_DEMO;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE STREAM_TRIP_EVENTS (
    EVENT_DATA VARIANT,
    SOURCE_FILE STRING,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT 'RAW.STREAM_TRIP_EVENTS table created' AS status;

---------------------------------
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MOBILITY_DEV;
USE DATABASE MOBILITY_DEMO;

--SELECT COUNT(*) AS raw_stream_event_count
--FROM RAW.STREAM_TRIP_EVENTS;

SELECT *
FROM RAW.STREAM_TRIP_EVENTS;

SELECT
    EVENT_DATA,
    SOURCE_FILE,
    LOADED_AT
FROM RAW.STREAM_TRIP_EVENTS
LIMIT 5;

---------------------------------
SELECT
    EVENT_DATA:event_id::STRING AS event_id,
    EVENT_DATA:event_type::STRING AS event_type,
    EVENT_DATA:event_ts::TIMESTAMP_TZ AS event_ts,
    EVENT_DATA:pickup_location_id::NUMBER AS pickup_location_id,
    EVENT_DATA:dropoff_location_id::NUMBER AS dropoff_location_id,
    EVENT_DATA:total_amount::FLOAT AS total_amount
FROM RAW.STREAM_TRIP_EVENTS
LIMIT 10;

---------------------------------
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE WH_MOBILITY_DEV;
USE DATABASE MOBILITY_DEMO;

DROP VIEW IF EXISTS GOLD.LIVE_ROUTE_METRICS;
DROP VIEW IF EXISTS GOLD.LIVE_PICKUP_ZONE_METRICS;
DROP VIEW IF EXISTS OPS.LIVE_STREAM_SUMMARY;
DROP VIEW IF EXISTS SILVER.STREAM_TRIP_EVENTS_CLEAN;

CREATE OR REPLACE TABLE RAW.STREAM_TRIP_EVENTS (
    EVENT_DATA VARIANT
);